alias x="vim ~/.xmonad/xmonad.hs"
alias xr="xmonad --recompile && xmonad --restart"
alias xb="vim ~/.xmobarrc"
alias sn="shutdown now"
alias dmen='dmenu_run -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15"'
